Dps 12
MarlonEnmanuel/devpractice-store pull request #10
Opened 2023-09-26 15:09 UTC by carloscruzado

Change Products  to DTO

2023-09-26 18:14 UTC, MarlonEnmanuel requested changes
Correcciones pendientes

2023-09-26 18:14 UTC, MarlonEnmanuel commented on Store.BD/Product.cs
> +        public DateTime expirationDate { get; set; }
Seguir la convención PascalCase para las propiedades de las clases

2023-09-26 18:14 UTC, MarlonEnmanuel commented on Store.BD/Product.cs
> +
Eliminar esta línea en blanco

2023-09-26 18:14 UTC, MarlonEnmanuel commented on Store.Services/Dtos/ProductDto.cs
> +    }
Sería bueno incluir las categorías en `ProductDto`

2023-09-26 18:14 UTC, MarlonEnmanuel commented on Store.Services/Dtos/SaveProductDto.cs
> +    }
En `SaveProductDto`, seria bueno recibir los IDs de las categorías a las que el producto está relacionado

2023-09-26 18:14 UTC, MarlonEnmanuel commented on Store.Services/ProductService.cs
> +                ProductNow.Name = product.Name;
En lugar de actualizar campo por campo, podrías usar el mismo automapper de la siguiente forma
`_mapper.map(saveProductDto, currentProduct);`
eso copia los datos del DTO a una entidad existente (en lugar de crear una nueva)

2023-09-26 18:14 UTC, MarlonEnmanuel commented on Store.Services/ProductService.cs
> +        public void Update(int id, SaveProductDto product)
un mejor nombre para el parámetro product sería `saveProductDto` o `productDto `o siemplmente `dto`

2023-09-26 18:14 UTC, MarlonEnmanuel commented on Store.Services/ProductService.cs
> +            var ProductNow = _context.Products.Find(id);
un mejor nombre para ProductNow sería `currentProduct`
usar la convención `camelCase `para variables locales

2023-10-03 23:27 UTC, carloscruzado commented on Store.Services/ProductService.cs
> +            var ProductNow = _context.Products.Find(id);
Se cambio a currentProduct

2023-10-03 23:27 UTC, carloscruzado commented on Store.Services/ProductService.cs
> +        public void Update(int id, SaveProductDto product)
se cambio a SaveProductDto

2023-10-03 23:32 UTC, carloscruzado commented on Store.Services/ProductService.cs
> +                ProductNow.Name = product.Name;
se cambio la funcionalidad _mapper

2023-10-03 23:33 UTC, carloscruzado commented on Store.BD/Product.cs
> +
se elimino la linea en blanco

2023-10-03 23:33 UTC, carloscruzado commented on Store.BD/Product.cs
> +        public DateTime expirationDate { get; set; }
se aplico la convención Pascal

2023-10-04 02:33 UTC, MarlonEnmanuel requested changes
Cambios de forma

2023-10-04 02:33 UTC, MarlonEnmanuel commented on Store.Api/Controllers/ProductController.cs
> +            [HttpGet]
Corregir tabulación

2023-10-04 02:33 UTC, MarlonEnmanuel commented on Store.Services/Dtos/ProductDto.cs
> +        public  List<CategoryDto>? Categories { get; set; }
Corregir formato

2023-10-04 02:33 UTC, MarlonEnmanuel commented on Store.Services/Dtos/SaveProductDto.cs
> +﻿
Eliminar línea

2023-10-04 02:33 UTC, MarlonEnmanuel commented on Store.Services/ProductService.cs
> +            var list = _context.Products.Include(p=>p.Categories).Include(p=>p.Brand).ToList();
Colocar cada método en una linea

2023-10-04 02:39 UTC, carloscruzado commented
update changes

2023-10-04 02:41 UTC, carloscruzado commented
update

2023-10-04 02:43 UTC, MarlonEnmanuel approved these changes
Todo OK

2023-10-04 02:43 UTC, merged