Aggree Logic de FluentValidation in the DTOs the Category
MarlonEnmanuel/devpractice-store pull request #13
Opened 2023-10-03 06:17 UTC by csamillan

Creando Logica de Fluent Validation para los DTOs Category

2023-10-03 16:43 UTC, MarlonEnmanuel requested changes
Correcciones de forma

2023-10-03 16:43 UTC, MarlonEnmanuel commented on Store.Services/CategoryService.cs
> +            ValidationResult result = _validator.Validate(dto);
Usemos el método `ValidateAndThrow`, en una sola línea se valida y se lanza excepción

2023-10-03 16:43 UTC, MarlonEnmanuel commented on Store.Services/Validator/SaveCategoryDtoValidator.cs
> +            RuleFor(x  => x.Name).NotEmpty()
Alinear hacia abajo desde el primer método
```
RuleFor(x  => x.Name)
    .NotEmpty()
    .NotNull()
    .MaximumLength(20);
```

2023-10-03 21:59 UTC, csamillan commented
Se realizo los ajustes solicitados

2023-10-04 02:14 UTC, MarlonEnmanuel requested changes
Cambios de forma

2023-10-04 02:14 UTC, MarlonEnmanuel commented on Store.Services/CategoryService.cs
> +using FluentValidation.Results;
Eliminar usings innecesarios

2023-10-04 02:14 UTC, MarlonEnmanuel commented on Store.Services/CategoryService.cs
>              var CategoryNow = _context.Categories.Find(id);
un mejor nombre es `currentCategory`

2023-10-16 23:09 UTC, MarlonEnmanuel approved these changes
Todo ok

2023-10-16 23:10 UTC, merged