Apply Dtos in the class Supplier
MarlonEnmanuel/devpractice-store pull request #15
Opened 2023-10-04 17:21 UTC by alberth270

2023-10-04 22:50 UTC, MarlonEnmanuel requested changes
Todo correcto, solo falta mejorar con los nombres de las funciones y variables (sigamos clean code)

2023-10-04 22:50 UTC, MarlonEnmanuel commented on Store.Api/Controllers/SupplierController.cs
> +        public IActionResult PostProvider(SaveSupplierDto supplier)
Corregir nombres de variables `supplierDto` o simplmente `dto`

2023-10-04 22:50 UTC, MarlonEnmanuel commented on Store.Services/Interface/ISupplierService.cs
> +        IList<SupplierDto> Get();
Podemos mejorar el nombre de las funciones y variables, que tegan sentido al leerlo (eso aplica al resto de clases)

2023-10-11 00:10 UTC, csamillan approved these changes

2023-10-11 00:11 UTC, csamillan approved these changes

2023-10-11 00:13 UTC, csamillan approved these changes

2023-10-11 00:15 UTC, csamillan approved these changes

2023-10-11 14:07 UTC, MarlonEnmanuel approved these changes
Todo ok

2023-10-11 14:07 UTC, merged