Dps 21 Change DTO  to Fluent Validation
MarlonEnmanuel/devpractice-store pull request #17
Opened 2023-10-12 01:20 UTC by carloscruzado

2023-10-12 02:28 UTC, MarlonEnmanuel requested changes
Corregir PR
También es necesario validar el DTO al actualizar

2023-10-12 02:28 UTC, MarlonEnmanuel commented on Store.Api/Controllers/ProductController.cs
> +using FluentValidation.Results;
Esta dependencia es innecesaria, siempre eliminar ussings innecesarios

2023-10-12 02:28 UTC, MarlonEnmanuel commented on Store.Services/ProductService.cs
> +        public ProductService(StoreDBContext context, IMapper mapper, IValidator<SaveProductDto> validator )
Conservar la separación vertical

2023-10-12 02:31 UTC, MarlonEnmanuel commented
Actualizar la rama con los últimos cambios de main

2023-10-12 21:55 UTC, carloscruzado commented on Store.Api/Controllers/ProductController.cs
> +using FluentValidation.Results;
corregido

2023-10-12 21:56 UTC, carloscruzado commented on Store.Services/ProductService.cs
> +        public ProductService(StoreDBContext context, IMapper mapper, IValidator<SaveProductDto> validator )
se dio separación  entre variables y función

2023-10-13 00:56 UTC, MarlonEnmanuel approved these changes
Todo ok

2023-10-13 00:56 UTC, merged