Dps 7 - Implement Brand functionality.
MarlonEnmanuel/devpractice-store pull request #7
Opened 2023-09-20 02:50 UTC by Gvzt

Dear Marlon, I am sending my changes. Please check it and accept.

2023-09-20 03:15 UTC, MarlonEnmanuel requested changes
Corregir observaciones

2023-09-20 03:15 UTC, MarlonEnmanuel commented on Store.Api/Controllers/CategoryController.cs
> +
Mover la clase `BrandController `a su propop archivo

2023-09-20 03:15 UTC, MarlonEnmanuel commented on Store.Api/Controllers/CategoryController.cs
> +        private readonly IBrandService brandService;
por estandar las propiedades privadas de un servicio inician con subguión

2023-09-20 03:15 UTC, MarlonEnmanuel commented on Store.BD/Brand.cs
> +using System.Text;
Eliminar ussing innecesarios

2023-09-20 03:15 UTC, MarlonEnmanuel commented on Store.BD/Product.cs
>          // foreigns
agregar linea en blando antes de `// foreings`

2023-09-20 03:15 UTC, MarlonEnmanuel commented on Store.Services/BrandService.cs
> +using System.Threading.Tasks;
Eliminar using innecesarios

2023-09-20 03:15 UTC, MarlonEnmanuel commented on Store.Services/BrandService.cs
> +    internal class BrandService
tiene que ser clase publica

2023-09-20 03:15 UTC, MarlonEnmanuel commented on Store.Services/BrandService.cs
> +    public interface IBrandService
agregar una linea en blanco antes

2023-09-27 01:13 UTC, Gvzt commented
Marlon, errors are already fixed

2023-09-27 01:16 UTC, MarlonEnmanuel approved these changes
Todo OK

2023-09-27 01:16 UTC, merged